### ISSUE TITLE
The most efficient

### ISSUE THREAD

**Issue by liangjiangliang** [encryptedsystems/Clusion#12]
Your design is excellent, but I want to know which one is the most efficient,thank you.

**Comment by orochi89** [comment]
Thanks! It really depends on what search functionality you want to support. Our recent added design, DLS, is the most efficient--when it comes to exact keyword search-- and provides interesting security properties (check the paper in the references if you want to learn more about the scheme). If you're looking for Boolean search, then you should use IEX.
