### ISSUE TITLE
java.lang.NoClassDefFoundError: org/crypto/sse/Printer

### ISSUE THREAD

**Issue by Shihui628** [encryptedsystems/Clusion#14]
My classmate and I followed the instructions from README.md but can not run the all steps in QuickTest. We occurred "java.lang.NoClassDefFoundError: org/crypto/sse/Printer"and "the main class could not be found or could not be loaded", and "the main class could not be initialized" Details are as followed:

<img width="1134" alt="wechat348e4203ae61e18fc543f52aff4fbe12" src="https://user-images.githubusercontent.com/25484968/51253519-7c913700-19d9-11e9-82a8-4f428147f868.png">

<img width="1920" alt="wechatimg1660" src="https://user-images.githubusercontent.com/25484968/51252149-0a6b2300-19d6-11e9-9e74-49b2411df4cb.png">

We are very confused and looking forward to a reply if there are similar situations or methods to handle our problems.

**Comment by Guss123** [comment]
Hi, I was not able to produce the errors you did. Is your classpath set properly? Can you post it here?

**Comment by Shihui628** [comment]
I also doubt at wrong class path setting but I use ‘echo $CLASSPATH’ to check it and still couldn’t find a solution. I captured my operations here, hoping this will do some help.

1. First, I download Clusion and put it in  /Users/shihuiwang/Clusion 
<img width="770" alt="e13acefc66f1a4aed9329eb2f993d180" src="https://user-images.githubusercontent.com/25484968/51760250-fa092580-2104-11e9-88b2-33d49e097b57.png">

2.Second, I open Terminal and run commands to build the jar.
Apache Maven 3.6.0 and Java jdk1.8.0_192.jdk is installed and because I’ve installed Clusion already, this step is very fast.

3.Here I come to the Quick Test. 
I set the classpath as :
export CLASSPATH=$CLASSPATH:/Users/shihuiwang/Clusion/target:/Users/shihuiwang/Clusion/target/test-classes

Also, I use 'echo $CLASSPATH' to check it. It shows that the class path is ‘
/Users/shihuiwang/Clusion/target:/Users/shihuiwang/Clusion/target/test-classes’
<img width="1004" alt="f022e70e5cb20f315fb45c346a1ffe82" src="https://user-images.githubusercontent.com/25484968/51760407-5409eb00-2105-11e9-9e61-1fba259fff23.png">

Then, when I try to run java org.crypto.sse.TestLocalRR2Lev, the error 'java.lang.NoClassDefFoundError: org/crypto/sse/Printer' occurs.
<img width="1004" alt="5d52c49b963314fcc5df4f4f65856981" src="https://user-images.githubusercontent.com/25484968/51760482-756ad700-2105-11e9-8ac4-39bebd0f64f7.png">

In other steps of Quick Test except the last one (to test IEX-2Lev on Amazon) , it occurs again. As to the last one (to test IEX-2Lev on Amazon) , 'Could not find or load main class org.crypto.sse.IEX2LevAMAZON' error occurs.
<img width="570" alt="7c852d8b-9f59-4bed-bfee-8ac81e0c0fa8" src="https://user-images.githubusercontent.com/25484968/51760760-36895100-2106-11e9-9d72-4576b563be2f.png">


The details of 'java.lang.NoClassDefFoundError: org/crypto/sse/Printer' for other steps sorted in the order in Quick Test are as follows .
<img width="570" alt="90f26015-e748-4095-b229-58f664c0e6d4" src="https://user-images.githubusercontent.com/25484968/51760854-7e0fdd00-2106-11e9-852b-edc8d7c4ab3a.png">
<img width="570" alt="61f4a3ad-4337-4889-8b4c-8d246fab484e" src="https://user-images.githubusercontent.com/25484968/51760863-823bfa80-2106-11e9-94de-f1e7a141dbd5.png">
<img width="570" alt="27e3d8c1-1e4e-496a-8e07-aded1af748e3" src="https://user-images.githubusercontent.com/25484968/51760878-8a943580-2106-11e9-91a6-9717e7193c72.png">
<img width="570" alt="a8f037d6-d67c-479e-bc36-249709406b4c" src="https://user-images.githubusercontent.com/25484968/51760885-8ec05300-2106-11e9-8b7d-404f9315b98b.png">
<img width="570" alt="97e06757-81f2-4049-94fc-ee5a40bf5afc" src="https://user-images.githubusercontent.com/25484968/51760900-95e76100-2106-11e9-9640-e77268396707.png">
<img width="570" alt="bedcb385-03c0-44ae-9c9a-2694664186c8" src="https://user-images.githubusercontent.com/25484968/51760903-9849bb00-2106-11e9-87cc-acb6fd1f02c6.png">
<img width="570" alt="385edaa8-4cfc-440a-9b32-db535e73bc0a" src="https://user-images.githubusercontent.com/25484968/51760906-9b44ab80-2106-11e9-920b-ec2979777d87.png">

**Comment by Guss123** [comment]
Thanks for the detailed response. Do me a favor and do the following steps:
export CLASSPATH=""

export CLASSPATH=$CLASSPATH:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT.jar:/Users/shihuiwang/Clusion/target/test-classes:.

echo $CLASSPATH
(and paste the result here, if the tests are still not working after this)

**Comment by Shihui628** [comment]
Thank you for your reply. The error "java.lang.NoClassDefFoundError" disappeared but here comes a new problem:"java.lang.NullPointerException". I am not sure whether it is caused by my improper operation.
I changed the class path according to your instruction, and the result of echo $CLASSPATH is:"

:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar
:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT.jar:/Users/shihuiwang/Clusion/target/test-classes

"
Then Terminal asked me to "Enter your password :"
I entered '123' as a test.
Then terminal showed 'Enter the relative path name of the folder that contains the files to make searchable'.
I have created a folder named 'testfolder' which contains three .doc files in the same path as the test classes. ( /Users/shihuiwang/Clusion/target/test-classes/org/crypto/sse/testfolder)
/Users/shihuiwang/Desktop/0B288A297769436E38A2277924C71BFD.png

Then the error occurred:

Enter the relative path name of the folder that contains the files to make searchable
testfolder
Exception in thread "main" java.lang.NullPointerException
at org.crypto.sse.TextProc.listf(TextProc.java:91)
at org.crypto.sse.TestLocalRR2Lev.main(TestLocalRR2Lev.java:46)

At 2019-01-26 04:03:27, "Guss123" <notifications@github.com> wrote:


Thanks for the detailed response. Do me a favor and do the following steps:
export CLASSPATH=""

export CLASSPATH=$CLASSPATH:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT.jar:/Users/shihuiwang/Clusion/target/test-classes:.

echo $CLASSPATH
(and paste the result here, if the tests are still not working after this)

**Comment by Shihui628** [comment]
> Thanks for the detailed response. Do me a favor and do the following steps:
> export CLASSPATH=""
> 
> export CLASSPATH=$CLASSPATH:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT-jar-with-dependencies.jar:/Users/shihuiwang/Clusion/target/Clusion-1.0-SNAPSHOT.jar:/Users/shihuiwang/Clusion/target/test-classes:.
> 
> echo $CLASSPATH
> (and paste the result here, if the tests are still not working after this)

Thank you! Your advice helps a lot.
