### ISSUE TITLE
error when building the jar

### ISSUE THREAD

**Issue by freelyyu** [encryptedsystems/Clusion#16]
I have installed Java and Maven. But when I run the commands `mvn clean install` to build the jar. It occurs some errors as follows:
![{W3}H{%Q5`FXYD82RWP2((D](https://user-images.githubusercontent.com/39991677/71765561-6bff0700-2f31-11ea-8bdf-eaeee6027572.png)
![K_$XT{BO1%~45G TTO7D9RJ](https://user-images.githubusercontent.com/39991677/71765556-61dd0880-2f31-11ea-94d4-8a8a2ba73d29.png)

**Comment by orochi89** [comment]
Thanks for pointing us to this error. There were some inconsistencies in the class path of some dependencies since their last updates. Now it should compile. Let us know if it does not.
